language: cpp
dist: trusty

addons:
  apt:
    sources:
      - llvm-toolchain-trusty
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - g++-5
      - zlib1g-dev
      - libhdf5-dev

matrix:
  include:
    - compiler: gcc
      env: CXX_COMPILER=g++-4.8 C_COMPILER=gcc-4.8 TOOLSET=gcc VISUAL_DEBUG=ON CCTAG_SERIALIZE=ON WITH_CUDA=ON
    - compiler: gcc
      env: CXX_COMPILER=g++-4.8 C_COMPILER=gcc-4.8 TOOLSET=gcc VISUAL_DEBUG=OFF CCTAG_SERIALIZE=ON WITH_CUDA=OFF
    - compiler: gcc
      env: CXX_COMPILER=g++-5 C_COMPILER=gcc-5 TOOLSET=gcc VISUAL_DEBUG=ON CCTAG_SERIALIZE=ON WITH_CUDA=ON
    - compiler: gcc
      env: CXX_COMPILER=g++-5 C_COMPILER=gcc-5 TOOLSET=gcc VISUAL_DEBUG=OFF CCTAG_SERIALIZE=ON WITH_CUDA=OFF
    - compiler: clang
      env: CXX_COMPILER=clang++ C_COMPILER=clang TOOLSET=clang VISUAL_DEBUG=OFF CCTAG_SERIALIZE=OFF WITH_CUDA=ON
    - compiler: clang
      env: CXX_COMPILER=clang++ C_COMPILER=clang TOOLSET=clang VISUAL_DEBUG=ON CCTAG_SERIALIZE=ON WITH_CUDA=OFF
    - compiler: clang
      env: CXX_COMPILER=clang++-3.8 C_COMPILER=clang-3.8 TOOLSET=clang VISUAL_DEBUG=OFF CCTAG_SERIALIZE=OFF WITH_CUDA=ON
    - compiler: clang
      env: CXX_COMPILER=clang++-3.8 C_COMPILER=clang-3.8 TOOLSET=clang VISUAL_DEBUG=ON CCTAG_SERIALIZE=ON WITH_CUDA=OFF


env:
  global:
    - NUM_CPU="`grep processor /proc/cpuinfo | wc -l`"; echo $NUM_CPU

script:
  - cc --version
  - c++ --version  
  - gcc --version
  - g++ --version  
  - cmake --version
  - ${CXX_COMPILER} --version
  - ${C_COMPILER} --version
  - echo "VISUAL_DEBUG=${VISUAL_DEBUG} CCTAG_SERIALIZE=${CCTAG_SERIALIZE} WITH_CUDA=${WITH_CUDA}"

