language: cpp
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - zlib1g-dev
            - libhdf5-dev
      env: COMPILER=g++-4.8
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-3.8
            - zlib1g-dev
            - libhdf5-dev
      env: COMPILER=clang-3.8

env:
  global:
    - NUM_CPU="`grep processor /proc/cpuinfo | wc -l`"; echo $NUM_CPU

script:
  - cc --version
  - c++ --version  
  - gcc --version
  - g++ --version  
  - cmake --version
  - ${COMPILER} --version

